--- #YAML:1.0
name:               File-Checkm
version:            0.02
abstract:           checkm (command) and routines to manage manifests
author:
    - John A. Kunze <jak@ucop.edu>
license:            BSD
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          0
    File::Find:    0
    Getopt::Long:  0
    Pod::Usage:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
